import { describe, it, expect, afterEach } from 'vitest';
import fc from 'fast-check';
import { renderHook, act } from '@testing-library/react';
import { render, screen, cleanup } from '@testing-library/react';
import { useFormValidation } from '../hooks/ui/useFormValidation.js';
import { FormField } from '../components/ui/forms/FormField.js';
import { z } from 'zod';

const testSchema = z.object({
  email: z.string().email('Invalid email'),
  age: z.number().min(18, 'Must be at least 18'),
});

describe('useFormValidation Hook', () => {
  afterEach(() => {
    cleanup();
  });

  it('Property 8: should reject invalid inputs and produce field-level errors', () => {
    const invalidEmails = fc.string().filter(s => !s.includes('@'));
    
    fc.assert(
      fc.property(invalidEmails, (email) => {
        try {
          const { result } = renderHook(() => useFormValidation(testSchema, { email: '', age: 20 }));
          
          act(() => {
            result.current.handleChange('email', email);
          });
          
          act(() => {
            result.current.handleBlur('email');
          });
          
          expect(result.current.isValid).toBe(false);
          expect(result.current.errors.email).toBe('Invalid email');
        } finally {
          cleanup();
        }
      }),
      { numRuns: 100 }
    );
  });
  
  it('should clear errors on valid change', () => {
    const { result } = renderHook(() => useFormValidation(testSchema, { email: '', age: 20 }));
    
    act(() => {
      result.current.handleChange('email', 'not-an-email');
      result.current.handleBlur('email');
    });
    
    expect(result.current.errors.email).toBe('Invalid email');
    
    act(() => {
      result.current.handleChange('email', 'valid@example.com');
    });
    
    expect(result.current.errors.email).toBeUndefined();
  });
});

describe('FormField Component', () => {
  afterEach(() => {
    cleanup();
  });

  it('Property 9: should map accessible error associations when error is provided', () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), fc.string({ minLength: 1 }), (name, errorMsg) => {
        try {
          render(<FormField label="Test Field" name={name} error={errorMsg} />);
          
          const input = screen.getByLabelText('Test Field');
          expect(input.getAttribute('aria-invalid')).toBe('true');
          
          const describedBy = input.getAttribute('aria-describedby');
          expect(describedBy).toBeTruthy();
          
          // Use DOM queries instead of RTL getByText which fails on whitespace-only strings generated by fast-check
          const errorMessage = document.getElementById(describedBy!);
          expect(errorMessage).not.toBeNull();
          expect(errorMessage?.textContent).toBe(errorMsg);
        } finally {
          cleanup();
        }
      })
    );
  });
  
  it('should not map error associations when error is undefined', () => {
    const { unmount } = render(<FormField label="Test Field" name="test" />);
    
    const input = screen.getByLabelText('Test Field');
    
    expect(input.getAttribute('aria-invalid')).toBe('false');
    expect(input.getAttribute('aria-describedby')).toBeNull();
    
    unmount();
  });
});
